name: Generate Tetris Page

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'  # Her 6 saatte çalışır

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Create dist directory and Tetris page
        run: |
          mkdir -p dist
          cat > dist/index.html << 'EOF'
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>Simple Tetris</title>
<style>
  body { margin:0; background:#222; display:flex; justify-content:center; align-items:center; height:100vh; }
  canvas { background:#000; display:block; }
</style>
</head>
<body>
<canvas id="tetris" width="240" height="400"></canvas>
<script>
// Minimal Tetris JS (örnek)
const canvas = document.getElementById('tetris');
const ctx = canvas.getContext('2d');
ctx.scale(20,20);

function drawSquare(x, y, color) {
  ctx.fillStyle = color;
  ctx.fillRect(x, y, 1, 1);
}

function draw() {
  ctx.fillStyle = '#000';
  ctx.fillRect(0,0,12,20);
  drawSquare(1,1,'red');
  drawSquare(2,1,'green');
  drawSquare(3,1,'blue');
}

draw();
</script>
</body>
</html>
EOF

      - name: Commit and push to output branch
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Update Tetris page'
          branch: output
          file_pattern: 'dist/**'
          push_options: '--force'
